// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsManagement.API.Data;

#nullable disable

namespace SportsManagement.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316220834_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportsManagement.API.Models.AiLineupSuggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SuggestionId"));

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedLineup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SuggestionId");

                    b.HasIndex("MatchId");

                    b.ToTable("AiLineupSuggestions");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RecordedByStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RecordedByStaffId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SportsManagement.API.Models.CoachingPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<int>("CreatorStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DrillFilesUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlanId");

                    b.HasIndex("CreatorStaffId");

                    b.ToTable("CoachingPlans");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SportsManagement.API.Models.FitnessRecord", b =>
                {
                    b.Property<int>("FitnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FitnessId"));

                    b.Property<float?>("Bmi")
                        .HasColumnType("real");

                    b.Property<float?>("BodyFatPercentage")
                        .HasColumnType("real");

                    b.Property<float?>("EnduranceScore")
                        .HasColumnType("real");

                    b.Property<int>("FitnessStaffId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<float?>("SpeedTestResult")
                        .HasColumnType("real");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FitnessId");

                    b.HasIndex("FitnessStaffId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FitnessRecords");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OpponentScore")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<int?>("ScoreKeeperStaffId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamScore")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ScoreKeeperStaffId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportsManagement.API.Models.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordId"));

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int>("DoctorStaffId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExpectedReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("InjuryType")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportFileUrl")
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.HasIndex("DoctorStaffId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerCumulativeStats", b =>
                {
                    b.Property<int>("PlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerStatId"));

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesStarted")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAssists")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFreeThrowsMade")
                        .HasColumnType("integer");

                    b.Property<float>("TotalGamesEfficiencyRating")
                        .HasColumnType("real");

                    b.Property<int>("TotalMinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPersonalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSteals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalThreePointsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurnovers")
                        .HasColumnType("integer");

                    b.HasKey("PlayerStatId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCumulativeStats");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("GameStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameStatId"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<string>("ClipsVideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("FieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("FieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<int>("FreeThrowsMade")
                        .HasColumnType("integer");

                    b.Property<float>("GameEfficiencyRating")
                        .HasColumnType("real");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rebounds")
                        .HasColumnType("integer");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("ThreePointsMade")
                        .HasColumnType("integer");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer");

                    b.HasKey("GameStatId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerProfile", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "System administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Team manager",
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Head or assistant coach",
                            Name = "Coach"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Registered player",
                            Name = "Player"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Medical staff",
                            Name = "Medic"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Performance analyst",
                            Name = "Analyst"
                        });
                });

            modelBuilder.Entity("SportsManagement.API.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeamId");

                    b.HasIndex("ManagerUserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamCumulativeStats", b =>
                {
                    b.Property<int>("TeamStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamStatId"));

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesStarted")
                        .HasColumnType("integer");

                    b.Property<float>("Per")
                        .HasColumnType("real");

                    b.Property<string>("SeasonYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAssists")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFreeThrowsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPointsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPointsScored")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSteals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalThreePointsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurnovers")
                        .HasColumnType("integer");

                    b.HasKey("TeamStatId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamCumulativeStats");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamGameStats", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("AnalystStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("FullMatchVideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("PointsScored")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryPdfUrl")
                        .HasColumnType("text");

                    b.Property<float>("TeamEfficiency")
                        .HasColumnType("real");

                    b.Property<int>("TotalAssists")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFreeThrowsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSteals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalThreePointsMade")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurnovers")
                        .HasColumnType("integer");

                    b.HasKey("ReportId");

                    b.HasIndex("AnalystStaffId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("StaffId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamStaff");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TrainingSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<int>("ConductedByStaffId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionNotes")
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("ConductedByStaffId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("SportsManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoogleUser")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportsManagement.API.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SportsManagement.API.Models.AiLineupSuggestion", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Match", "Match")
                        .WithMany("AiLineupSuggestions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Announcement", b =>
                {
                    b.HasOne("SportsManagement.API.Models.User", "Creator")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("Announcements")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Attendance", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.PlayerProfile", "Player")
                        .WithMany("Attendances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.TeamStaff", "RecordedByStaff")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("RecordedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Player");

                    b.Navigation("RecordedByStaff");
                });

            modelBuilder.Entity("SportsManagement.API.Models.CoachingPlan", b =>
                {
                    b.HasOne("SportsManagement.API.Models.TeamStaff", "CreatorStaff")
                        .WithMany("CoachingPlans")
                        .HasForeignKey("CreatorStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorStaff");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Event", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("Events")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsManagement.API.Models.FitnessRecord", b =>
                {
                    b.HasOne("SportsManagement.API.Models.TeamStaff", "FitnessStaff")
                        .WithMany("FitnessRecords")
                        .HasForeignKey("FitnessStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.PlayerProfile", "Player")
                        .WithMany("FitnessRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessStaff");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Match", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Event", "Event")
                        .WithOne("Match")
                        .HasForeignKey("SportsManagement.API.Models.Match", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.TeamStaff", "ScoreKeeperStaff")
                        .WithMany()
                        .HasForeignKey("ScoreKeeperStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("ScoreKeeperStaff");
                });

            modelBuilder.Entity("SportsManagement.API.Models.MedicalRecord", b =>
                {
                    b.HasOne("SportsManagement.API.Models.TeamStaff", "DoctorStaff")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.PlayerProfile", "Player")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorStaff");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Message", b =>
                {
                    b.HasOne("SportsManagement.API.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerCumulativeStats", b =>
                {
                    b.HasOne("SportsManagement.API.Models.PlayerProfile", "Player")
                        .WithMany("CumulativeStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerGameStats", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Match", "Match")
                        .WithMany("PlayerGameStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.PlayerProfile", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerProfile", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("SportsManagement.API.Models.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Team", b =>
                {
                    b.HasOne("SportsManagement.API.Models.User", "Manager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamCumulativeStats", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("CumulativeStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamGameStats", b =>
                {
                    b.HasOne("SportsManagement.API.Models.TeamStaff", "AnalystStaff")
                        .WithMany("AnalyzedStats")
                        .HasForeignKey("AnalystStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportsManagement.API.Models.Match", "Match")
                        .WithOne("TeamGameStats")
                        .HasForeignKey("SportsManagement.API.Models.TeamGameStats", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalystStaff");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamStaff", b =>
                {
                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("Staff")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.User", "User")
                        .WithMany("StaffRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TrainingSession", b =>
                {
                    b.HasOne("SportsManagement.API.Models.TeamStaff", "ConductedByStaff")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("ConductedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.Event", "Event")
                        .WithOne("TrainingSession")
                        .HasForeignKey("SportsManagement.API.Models.TrainingSession", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.CoachingPlan", "Plan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConductedByStaff");

                    b.Navigation("Event");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SportsManagement.API.Models.User", b =>
                {
                    b.HasOne("SportsManagement.API.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");
                });

            modelBuilder.Entity("SportsManagement.API.Models.UserRole", b =>
                {
                    b.HasOne("SportsManagement.API.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.API.Models.Team", "Team")
                        .WithMany("UserRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportsManagement.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsManagement.API.Models.CoachingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Event", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Match");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Match", b =>
                {
                    b.Navigation("AiLineupSuggestions");

                    b.Navigation("PlayerGameStats");

                    b.Navigation("TeamGameStats");
                });

            modelBuilder.Entity("SportsManagement.API.Models.PlayerProfile", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CumulativeStats");

                    b.Navigation("FitnessRecords");

                    b.Navigation("GameStats");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SportsManagement.API.Models.Team", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("CumulativeStats");

                    b.Navigation("Events");

                    b.Navigation("Players");

                    b.Navigation("Staff");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SportsManagement.API.Models.TeamStaff", b =>
                {
                    b.Navigation("AnalyzedStats");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("CoachingPlans");

                    b.Navigation("FitnessRecords");

                    b.Navigation("MedicalRecords");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("SportsManagement.API.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ManagedTeams");

                    b.Navigation("PlayerProfile");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("StaffRoles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
